[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.deploy-preview.environment]
  NETLIFY_USE_YARN = true

[context.branch-deploy.environment]
  NETLIFY_USE_YARN = true